spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa-shop
    username: shop_admin
    password: q1w2e3

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      # show_sql: true -> System.out 으로 출력
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # logger 를 통해서 출력 (권장)